language: python
python:
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: cbini
  password:
    secure: LmyrZDnwmPWeAJ6O9BLgIQTLr2QoJrR6Pg/Pu+QsTFkDE38VAx+vwDIIwVh4l8w0pUsRVYsXaykYB0I4JWJo22AYpkk95GPAPsWJMq1G7d67UIDtds5RKMy3Xs5CUCQjyUEdAdZaxu/d+gZDVtUIv9zKzZh60U9dSOl8hNrATqdnITrmoOlQyBOJabZnCIBLsA5NY/Jv6bkmgHkzqhtFTYy3ROPYcQtEaySOBxVa+HxBv8g8qGwE/lchGSr0BNkIVgWIMi6vMjxx4gDyChCPYD+hwQYq6Zh1YjjTg6ao5GEXqCACa5SVv9+2/HhEKvvWRevOtXPa42a6tlrWKJvRD+Mif/dTNazlkarWdZC7nuof/2mqxvLzNAcFPPOgpmVsZaaGD3HvNw3jYJ7nJ6hJxVijAiZ7rlnhKn66Gx4ZilW5unVHakrdiepLYgu3AVshd7lO2lG1afSsR2pA3kMelfda0N0Vy31FGec2FqtA+hZZ62wsPOuM7js23Kz11NaIR2FIswJMdaNCOpAkxfn5BTa3t42AYoGyG9od2CUOwqw/imlNuoK2+lIiPQZPSD89nI1uGytYC6YlJAg7dTXPe5hOez4Nh768wfosHy6h2XC6M4xTXvizGRnfp2vz84vgPJRL0yGzRKKTaM+dPiO5v6wXs9KPjUB4OcoE3NzLoEc=
  on:
    tags: true
    repo: cbini/whetstone
    python: 3.8
